[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@solmate-utils/=lib/solmate/src/utils/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]

gas_reports = ["*"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL"

[etherscan]
sepolia = { key = "$S{ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
